Preprocessing titanic data set for Classification

In [1]:
import pandas as pd #used for data analysis
import numpy as np  #used for performing mathematical operations on arrays

import matplotlib.pyplot as plt  #is used to plot visualization graphs
import seaborn as sns  #used for data visualization and data anlysis

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler

In [114]:
file_path = '/content/titanic_original.csv'
df = pd.read_csv(file_path)
df_Tour = df.copy()
print(f'there are {df_Tour.shape[0]} rows , and {df_Tour.shape[1]} columns')

there are 1310 rows , and 14 columns

In [115]:
df_Tour.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [116]:
print('number of rows: ', df_Tour.shape[0])
print('number of columns: ', df_Tour.shape[1])
print('features are: ' , df_Tour.columns.tolist())
print('\n')

number of rows:  1310
number of columns:  14
features are:  ['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket', 'fare', 'cabin', 'embarked', 'boat', 'body', 'home.dest']

In [117]:
print('Duplicated values are: \n', df_Tour.duplicated().sum())

Duplicated values are:
 0

In [118]:
print('Missing values are: \n', df_Tour.isnull().sum().sort_values(ascending=False))

Missing values are:
 body         1189
cabin        1015
boat          824
home.dest     565
age           264
embarked        3
fare            2
pclass          1
survived        1
name            1
sex             1
sibsp           1
parch           1
ticket          1
dtype: int64

In [119]:
# Handling missing values
df_Tour = df_Tour.drop(columns=['body','cabin','boat','home.dest','name'])

In [120]:
df_Tour.head()

   pclass  survived     sex      age  sibsp  parch  ticket      fare embarked
0     1.0       1.0  female  29.0000    0.0    0.0   24160  211.3375        S
1     1.0       1.0    male   0.9167    1.0    2.0  113781  151.5500        S
2     1.0       0.0  female   2.0000    1.0    2.0  113781  151.5500        S
3     1.0       0.0    male  30.0000    1.0    2.0  113781  151.5500        S
4     1.0       0.0  female  25.0000    1.0    2.0  113781  151.5500        S

In [121]:
df_Tour['age'] = df_Tour['age'].fillna(df_Tour['age'].median())

In [122]:
print('Missing values are: \n', df_Tour.isnull().sum().sort_values(ascending=False))

Missing values are:
 embarked    3
fare        2
pclass      1
survived    1
sex         1
sibsp       1
parch       1
ticket      1
age         0
dtype: int64

In [123]:
df_Tour['embarked'].value_counts()

embarked
S    914
C    270
Q    123
Name: count, dtype: int64

In [124]:
df_Tour['embarked'] = df_Tour['embarked'].fillna('S')

In [125]:
df_Tour['fare'] = df_Tour['fare'].fillna(method='ffill')
df_Tour['pclass'] = df_Tour['pclass'].fillna(method='ffill')
df_Tour['survived'] = df_Tour['survived'].fillna(method='ffill')
df_Tour['sex'] = df_Tour['sex'].fillna(method='ffill')
df_Tour['sibsp'] = df_Tour['sibsp'].fillna(method='ffill')
df_Tour['parch'] = df_Tour['parch'].fillna(method='ffill')
df_Tour['ticket'] = df_Tour['ticket'].fillna(method='ffill')

<ipython-input-125-b9d89eb5a4cc>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_Tour['fare'] = df_Tour['fare'].fillna(method='ffill')
<ipython-input-125-b9d89eb5a4cc>:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_Tour['pclass'] = df_Tour['pclass'].fillna(method='ffill')
<ipython-input-125-b9d89eb5a4cc>:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_Tour['survived'] = df_Tour['survived'].fillna(method='ffill')
<ipython-input-125-b9d89eb5a4cc>:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_Tour['sex'] = df_Tour['sex'].fillna(method='ffill')
<ipython-input-125-b9d89eb5a4cc>:5: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_Tour['sibsp'] = df_Tour['sibsp'].fillna(method='ffill')
<ipython-input-125-b9d89eb5a4cc>:6: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_Tour['parch'] = df_Tour['parch'].fillna(method='ffill')
<ipython-input-125-b9d89eb5a4cc>:7: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_Tour['ticket'] = df_Tour['ticket'].fillna(method='ffill')

In [126]:
print('Missing values are: \n', df_Tour.isnull().sum().sort_values(ascending=False))

Missing values are:
 pclass      0
survived    0
sex         0
age         0
sibsp       0
parch       0
ticket      0
fare        0
embarked    0
dtype: int64

In [127]:
df_Tour.head()

   pclass  survived     sex      age  sibsp  parch  ticket      fare embarked
0     1.0       1.0  female  29.0000    0.0    0.0   24160  211.3375        S
1     1.0       1.0    male   0.9167    1.0    2.0  113781  151.5500        S
2     1.0       0.0  female   2.0000    1.0    2.0  113781  151.5500        S
3     1.0       0.0    male  30.0000    1.0    2.0  113781  151.5500        S
4     1.0       0.0  female  25.0000    1.0    2.0  113781  151.5500        S

In [128]:
# Encoding Categorical Variables

df_Tour['embarked'] = df_Tour['embarked'].astype('category')
df_Tour['embarked'] = df_Tour['embarked'].cat.codes

df_Tour['sex'] = df_Tour['sex'].astype('category')
df_Tour['sex'] = df_Tour['sex'].cat.codes

df_Tour.head()

   pclass  survived  sex      age  sibsp  parch  ticket      fare  embarked
0     1.0       1.0    0  29.0000    0.0    0.0   24160  211.3375         2
1     1.0       1.0    1   0.9167    1.0    2.0  113781  151.5500         2
2     1.0       0.0    0   2.0000    1.0    2.0  113781  151.5500         2
3     1.0       0.0    1  30.0000    1.0    2.0  113781  151.5500         2
4     1.0       0.0    0  25.0000    1.0    2.0  113781  151.5500         2

In [129]:
# Saving the dataset as a CSV file
df_Tour.to_csv('clean-Titanic.csv', index=False)